### PR TITLE
Section 4: Updated content keys and FR translation

### PR DESCRIPTION
**Pull request by jeffmaher**
# Description

[Trello card:](https://trello.com/c/a46aCfHK/309-people-can-access-prototype-in-en-and-fr) Translates section 4 of the medical report into French

# Test Instructions

1. Go to the application
1. If your browser is in EN-xx locale, click `Français` at the top
1. Navigate through the intro section, Section 1, Section 2, and Section 3 to get to Section 4 (alternately, change the URL to `/fr/frsection4`)
1. See French translation (original EN and FR forms are linked in the [Trello card](https://trello.com/c/a46aCfHK/309-people-can-access-prototype-in-en-and-fr))

# Help Requested

If there are any things you spot that are issues we should come back to, but are out of scope of just the direct translation, please add a new Trello card or [use this one to quickly add a note to the checklist](https://trello.com/c/WqJVeqsh/356-misc-content-tasks).

### CODE REVIEW

**Comment by jeffmaher** [comment]
@kylejones-ESDC : Can you review this? If there's anything that needs to be correct, post back here and/or request changes. If everything looks OK, can you add Dave or Calvin as a reviewer?

**Comment by kylejones-ESDC** [comment]
- Was not super obvious to me how the system wanted it formatted.  i.e. making sure to place spaces or dashes between numbers.  Can it be designed such that there is a separate box for each of the 3 digits in the SIN, Phone number, and similarly have separate boxes for each component of the address?
- Will not accept any SIN format.

**Comment by jeffmaher** [comment]
Holding off until after research and resetting the codebase after that.

**Comment by jeffmaher** [comment]
@kylejones-ESDC : I think that's in a different section and is a different scope than this translation. Could you add that idea to this card: https://trello.com/c/WqJVeqsh/356-misc-content-tasks ?

**Comment by jeffmaher** [comment]
For the SIN, I've just been using `443856299`.

**Comment by kylejones-ESDC** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Hi Jeff,I'm afraid I dont follow.  I commented on what I was seeing when I viewed the pull request.  The link you provided does not work.Kyle                                                                                                                                             Sent from my BlackBerry — the most secure mobile device                                                                                                                                                                           From: notifications@github.comSent: November 22, 2019 1:57 PMTo: cppd-medical-report@noreply.github.comReply to: reply@reply.github.comCc: kyle.jones@cds-snc.ca; mention@noreply.github.comSubject: Re: [cds-snc/cppd-medical-report] Section 4: Updated content keys and FR translation (#53)  @kylejones-ESDC : I think that's in a different section and is a different scope than this translation. Could you add that idea to this card: https://trello.com/c/WqJVeqsh/356-misc-content-tasks ?

**Comment by jeffmaher** [comment]
No worries -- let's chat on Monday. Have a good weekend!

**Comment by kylejones-ESDC** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Hey Jeff,I'm off until wednesday afternoon.Let's have a meeting to discuss how we can be giving timely feedback.  I have only tomorrow to have received notification about this one single page and have not been able to comment on other sections.Best,Kyle                                                                                                                                             Sent from my BlackBerry — the most secure mobile device                                                                                                                                                                           From: notifications@github.comSent: November 22, 2019 3:06 PMTo: cppd-medical-report@noreply.github.comReply to: reply@reply.github.comCc: kyle.jones@cds-snc.ca; mention@noreply.github.comSubject: Re: [cds-snc/cppd-medical-report] Section 4: Updated content keys and FR translation (#53)  No worries -- let's chat on Monday. Have a good weekend!

**Comment by jeffmaher** [comment]
Awaiting merge of #89 before work can continue on this.

**Comment by jeffmaher** [comment]
Changes merged in from #89 and ready for review. Since @kylejones-ESDC is at a conference, going to swap in @michellengaiCDS .

@michellengaiCDS : Let's chat on Wednesday to make sure we don't jump over Kyle's comments (above).

**Review by dsamojlenko — DISMISSED** [review]

**Comment by michellengaiCDS** [comment]
looks good to me!

**Review by CalvinRodo — APPROVED** [review]

**Pull request merged**
