### PR TITLE
Added French translations for edit buttons

### PR DESCRIPTION
**Pull request by jeffmaher**
# Description

https://trello.com/c/0ZLpEUXD/406-translate-links-for-edit-conditions-edit-medications-and-edit-treatments-to-french

# Test Instructions

- Navigate through the application, adding at least 1 condition, treatment, and medication
- Check for a French translation of the edit buttons on the condition, treatment, and medication list pages

### CODE REVIEW

**Comment by jeffmaher** [comment]
Conditions and medications are working. Investigating why treatments aren't rendering translations.

**Comment by jeffmaher** [comment]
User error :-) It's working, it just flipped back to English, which is a separate bug.

**Comment by jeffmaher** [comment]
@keithiopia : Can you review? If it looks OK, pass it to Dave. Otherwise, let me know what I should fix.

**Review by dsamojlenko — APPROVED** [review]
LGTM 🌮

**Review by keithiopia — APPROVED** [review]
Looks good to me too

**Pull request merged**
