### PR TITLE
Translate Section 8 / Supporting Documents to French

### PR DESCRIPTION
**Pull request by jeffmaher**
# Description

[Trello card:](https://trello.com/c/a46aCfHK/309-people-can-access-prototype-in-en-and-fr) Translates section 8 / supporting docs of the medical report into French.

# Test Instructions

1. Go to the application (from the linked "View Deployment")
1. Change the URL to `.../fr/documents` from `.../en/start`)
1. See French translation (original EN and FR forms are linked in the [Trello card](https://trello.com/c/a46aCfHK/309-people-can-access-prototype-in-en-and-fr))

# Help Requested

If there are any things you spot that are issues we should come back to, but are out of scope of just the direct translation, please add a new Trello card or [use this one to quickly add a note to the checklist](https://trello.com/c/WqJVeqsh/356-misc-content-tasks).

### CODE REVIEW

**Comment by jeffmaher** [comment]
@megberetta : Excited to get your review on this, as I think my translation is really bad. Couldn't remember how familiar you are with PR reviews, so invited you to a session with Shannon this afternoon.

**Comment by jeffmaher** [comment]
Reaching out to Michel for support on this one.

**Comment by jeffmaher** [comment]
Per standup, e-mailed Michel the lines that need to be translated.

**Comment by jeffmaher** [comment]
[Attach any notes or documents that are relevant to your patient.docx](https://github.com/cds-snc/cppd-medical-report/files/3906406/Attach.any.notes.or.documents.that.are.relevant.to.your.patient.docx)

Got translations from Michel. Will implement.

**Comment by jeffmaher** [comment]
@megberetta : Ready for your review!

**Comment by megberetta** [comment]
Please change to: Je joindrai des documents à l'appui plus tard

**Review by megberetta — COMMENTED** [review]
Sounds good

**Review by megberetta — DISMISSED** [review]

**Comment by jeffmaher** [comment]
Ready to merge after an approve.

**Review by dsamojlenko — APPROVED** [review]

**Pull request merged**
