### PR TITLE
Adding section 3 translations

### PR DESCRIPTION
**Pull request by CalvinRodo**
# Description

Added keys and translations for section 3

https://trello.com/c/a46aCfHK/309-people-can-access-prototype-in-en-and-fr

# Test Instructions

1. navigate to */fr/section3
1. ensure that french text is there. 

# Help Requested

- check that the french text matches what's in the french form

### CODE REVIEW

**Comment by adriannelee** [comment]
(Correct URL is actually *fr/frsection3)

**Review by adriannelee — DISMISSED** [review]
YYYY-MM-DD should be AAAA-MM-JJ

**Comment by jeffmaher** [comment]
Tip for @CalvinRodo : There is a `year_month_day_format` translation key coming with section 1 if we merge that in first.

**Comment by jeffmaher** [comment]
Holding off until after research and resetting the codebase after that.

**Comment by jeffmaher** [comment]
Awaiting merge of #89 before work can continue on this.

**Review by dsamojlenko — APPROVED** [review]
LGTM

**Pull request merged**
