### PR TITLE
README and file cleanup from node-starter-repo

### PR DESCRIPTION
**Pull request by jeffmaher**
Updated `README.md` to not have all the starter repo text and have setup instructions. Also, moved a bunch of relevant starter repo text to `docs/Dev Basics.md` and removed deployment code that we're unlikely to use anytime soon (and could get out of date rapidly).

### CODE REVIEW

**Review by CalvinRodo — APPROVED** [review]
Looks good

**Comment by jeffmaher** [comment]
Whoops -- looks like I forgot to sign some commits. Will re-issue the PR.

**Review by dsamojlenko — APPROVED** [review]
🌮

**Comment by jeffmaher** [comment]
Opened #27 , which is this, but with signed commits.

**Pull request closed without merging**
