### PR TITLE
Pull in upstream changes

### PR DESCRIPTION
**Pull request by dsamojlenko**
Pulls in some upstream changes from the node-starter-app repo (fixes Docker build)

### CODE REVIEW

**Comment by timarney** [comment]
Another fix is coming down the pipe soon from upstream.

**Comment by timarney** [comment]
Released 5.0.4

**Comment by dsamojlenko** [comment]
Thanks @timarney!

**Review by jeffmaher — APPROVED** [review]
LGTM! Tested out.

A thing we should do in the future for the node-starter-app is make the Dockerfile's default run not require the webpack-cli. Running `docker run` requires an interactive terminal to say `yes` to the install `webpack-cli`. (I'll add this to my to do list)

**Pull request merged**
