### PR TITLE
Added French text for LICENSE

### PR DESCRIPTION
**Pull request by jeffmaher**

### CODE REVIEW

**Review by obrien-j — COMMENTED** [review]
We typically don't recommend translating the license @jeffmaher .. It's something that's come up a few times.  

Also, there's a typo on the Copyright line. ;)

**Review by CalvinRodo — COMMENTED** [review]
I'm going to ask  about french license text, my understanding is that license legal either doesn't have to be or shouldn't be translated to french.

**Comment by jeffmaher** [comment]
@dsamojlenko, @CalvinRodo : Grabbed it from here: https://github.com/cds-snc/.github/blob/master/LICENSE (this was taken from WxT originally, and reviewed by Elise).

Will fix typo though!

**Review by CalvinRodo — COMMENTED** [review]
So WET did translate but when we had a chat with TBS legal a few years ago the recomendation was not to translate since it's a legal document and the English language has been tested in court but French translation hasn't.

**Comment by jeffmaher** [comment]
Ah - got it. Will ditch this PR. Thanks for the info!

**Pull request closed without merging**
