### PR TITLE
Section 2 French Translation

### PR DESCRIPTION
**Pull request by jeffmaher**
# Description

[Trello card:](https://trello.com/c/a46aCfHK/309-people-can-access-prototype-in-en-and-fr) Translates section 2 of the medical report.

# Test Instructions

1. Go to the application
1. If your browser is in EN-xx locale, click `Français` at the top
1. Navigate through the intro section and Section 1 to get to Section 2
1. See French translation (original EN and FR forms are linked in the Trello card)

### CODE REVIEW

**Comment by jeffmaher** [comment]
@shannd : Can you review via the "View Deployment" link? If anything looks crazy different from the paper form, can you comment in here and request changes? If everything looks OK, can you tag Dave or Calvin for a review?

**Comment by jeffmaher** [comment]
Holding off until after research and resetting the codebase after that.

**Comment by jeffmaher** [comment]
Awaiting merge of #89 before work can continue on this.

**Review by dsamojlenko — DISMISSED** [review]

**Review by shannd — CHANGES_REQUESTED** [review]
Required is in English 
Signature of applicant / authorized representative is in English

**Review by shannd — CHANGES_REQUESTED** [review]
- Regelement sur le Regime de pensions du Canada should be italicized. 
- The rest of the content in this section is out of order after the "remarque : tout oubli..."  Please see the french medical report to make changes.

**Comment by jeffmaher** [comment]
@shannd : Thanks for spotting those! Fixed the italicized text, and fixed the order.

**Comment by jeffmaher** [comment]
Chatted with @shannd and she said she'd pick back up tomorrow.

**Review by shannd — CHANGES_REQUESTED** [review]
-Should there be a red asterisk above the second paragraph? I don't have an issue with it, but it doesn't mirror the French form. 
-Should there be "obligatoire" above the j'autorise? Personally, I like it but it doesn't mirror the french form. 
- "(lettres moulees)" is missing. On the form it is beside "prenom du temoin". But not sure if that is important or what it means. 
-"trois ans" in last group of words under signature should be bolded.

**Comment by jeffmaher** [comment]
@shannd : Thanks for the feedback!

- The asterisk is more of a design change than a content change, so that'd fall out of scope. It's inline with all the required fields elsewhere in the application. If we want to change that, let's handle that in a task's scope.
- Similar to the asterisk, it's inline with the design of required fields elsewhere in the application.
- `lettres moulees` is a replacement for "print", but since this is digital, it's not relevant.
- Fixed the bolded text `trois ans`.

Ready for re-review!

**Review by shannd — CHANGES_REQUESTED** [review]
Looks great! 
- only thing is that that the "trois ans" did not show up as bolded "<strong>trois ans</strong>"

**Review by shannd — CHANGES_REQUESTED** [review]
- Still not showing up as bolded, showing up as this without the spaces <strong> trois ans </strong> weird that shows up as bold for me when I copy-pasted it in <strong>trois ans</strong>

**Comment by jeffmaher** [comment]
Will check it out and get a fix in later today. Thanks for spotting!

**Review by shannd — APPROVED** [review]
Looks great!

**Pull request merged**
